### ISSUE TITLE
Add function `pbd_get_exp_n_lineages_pb` (not _pbd)

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cer_raket#14]
Equations 14 and 15 state the number of expected lineages for the Protacted Birth (not death) model. Add it.

**Comment by richelbilderbeek** [comment]
Nope, I am only ten percent sure. Perhaps the right equations are in the Supplementary Material. I can look it up if you really want to, but you could also volunteer to do so.

Will you look up the right equation(s)?

**Comment by J-Damhuis** [comment]
I'll look for them tomorrow. If I can't find them I'll let you know.

**Comment by richelbilderbeek** [comment]
:+1: 

Note that tomorrow I may be very hard to reach: I will have to submit my article as a Microsoft Word document :sob:

**Comment by richelbilderbeek** [comment]
@J-Damhuis and @Tomdkkr : I have finished my final article submission and am available again up until 14:30.

**Comment by J-Damhuis** [comment]
I think I've found the right equations. I'm currently making sure I haven't made any stupid mistakes and then I'll put the function on raket so you can check if I did indeed use the right equations.

**Comment by richelbilderbeek** [comment]
Awesome! Merge with develop to get rid of the @lintr-bot comments.

**Comment by richelbilderbeek** [comment]
@J-Damhuis I see in [your](https://github.com/richelbilderbeek/raket/commit/728eb6d1dfa7750e90e0f00cd976279029aa43e1) you forgot to write/add the tests. 

From [The Pragmatic Programmer](https://github.com/HugoMatilla/The-Pragmatic-Programmer#43-ruthless-testing):

> Tip 63: Coding Ain't Done 'Til All the Tests Run

Please add these tests :+1:

**Comment by J-Damhuis** [comment]
@Tomdkkr told me he wanted to write the tests so that's why I haven't done them. I've tested the equations by hand though.

**Comment by richelbilderbeek** [comment]
Ah, that's just great! I will then just wait patiently :angel:

**Comment by Tomdkkr** [comment]
@richelbilderbeek @J-Damhuis added the tests to `pbd_get_exp_n_lineages_pb`

**Comment by richelbilderbeek** [comment]
Well done! You've tested for errors and output well.

I do expect that you test an equation by calling with some parameters. Sure, some may be zeroes, but I do expect at least one hand-calculated check if the outcome of the function is right one,

Hope you will do so: errors are known to lurk in long-big-equation-land :+1:

**Comment by J-Damhuis** [comment]
Done now
