### ISSUE TITLE
Vignette freezes build

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cer_raket#16]
The build freezes when [creating vignettes](https://travis-ci.org/richelbilderbeek/raket/builds/382080248#L1608) since [this commit](https://github.com/richelbilderbeek/raket/commit/53206d34191b4e183d60df5fc18718b07456e57f) by @J-Damhuis.

@J-Damhuis : I assume you try to fix it? 
 * If yes, please assign you to this. I think the commit is great, just the vignette struggling too long with the new sampling methods. 
 * If no, you can assign me to fix it

Cheers, Richel

**Comment by J-Damhuis** [comment]
It's fixed as of [this commit](https://github.com/richelbilderbeek/raket/commit/5b9d70678f517e6e8239cc98bd292ad7fb0aabee).
