### ISSUE TITLE
PBD::pbd_sim and pbd_sim_checked must give same results

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cer_raket#17]
Labeled it with `Issue #17`

**Comment by J-Damhuis** [comment]
[Done](https://github.com/richelbilderbeek/raket/commit/f352fae076bfc2c75c8979ebbd8cb64eb1ad328e)

**Comment by richelbilderbeek** [comment]
Could not have done so better myself :+1:
