### ISSUE TITLE
Fix samplemethod 'longest'

### ISSUE THREAD

**Issue by J-Damhuis** [richelbilderbeek/cer_raket#18]
It's because of the way the PBD trees are simulated using soc=2.
The order of IDs is not the same order as the order of speciation initiation time.
This messes with the logic I added to the 'shortest' and 'longest' sample methods.
I think I can get aroud this myself by making a copy of the tree, re-ordering it and changing the IDs.

**Comment by J-Damhuis** [comment]
Okay, this was not the problem. I've nearly fixed it now, but I'm still struggling with one syntax. How can I check if no values in a column are equal to -1e10 using a while loop? @richelbilderbeek

**Comment by richelbilderbeek** [comment]
```{r}
# df is a data frame
# 3 is column index
testit::assert(any(df[, 3] != -1e10))

**Comment by richelbilderbeek** [comment]
I guess I should @J-Damhuis :-)

**Comment by richelbilderbeek** [comment]
Just testing 10K times will already convince me. This test should either run in less then 5 secs, or run on Travis only. Feel free to pick either.

**Comment by J-Damhuis** [comment]
I believe I got 'longest' to work in [this commit](https://github.com/richelbilderbeek/PBD/commit/c1dd0d1de6102edf170bbba871f820c141ac4ae7). Leaving this issue open until it's sufficiently tested.

**Comment by richelbilderbeek** [comment]
Well done, I look forward to some thorough tests :+1:

**Comment by J-Damhuis** [comment]
Let 'pbd_find_scenario' run for 15-20 minutes to test both 'shortest' and 'longest'. Nothing came up, so I will close this issue.
