### ISSUE TITLE
peregrine error

### ISSUE THREAD

**Issue by Tomdkkr** [richelbilderbeek/cer_raket#19]
Hoi Richel,

sbatch: error: Batch script contains DOS line breaks (\r\n)
sbatch: error: instead of expected UNIX line breaks (\n).

even snel gegoogled maar dit is volgens mij een linux - windows probleempje. 

Groeten, Tom

**Comment by J-Damhuis** [comment]
@richelbilderbeek @richelbilderbeek @richelbilderbeek

**Comment by richelbilderbeek** [comment]
Use `dos2unix` to convert. Or use git to do the conversion for you.

**Comment by richelbilderbeek** [comment]
```
dos2unix myfile
```

or put `myfile` in a GitHub (e.g. `cer_raket`), push from your local computer, pull on Peregrine.

**Comment by J-Damhuis** [comment]
We got it to work now, thank you!

**Comment by Tomdkkr** [comment]
thanks :)

**Comment by richelbilderbeek** [comment]
Indeed, I see it running on `s2936941`! Well done!
