### ISSUE TITLE
Add `shortest` and `longest` in PBD::sampletree

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cer_raket#2]
Could also be called: 'Implement suggestion at [PBD issue 17](https://github.com/rsetienne/PBD/issues/17)'.

**Comment by richelbilderbeek** [comment]
Will present this at the TECE day of May 2nd 2018.

**Comment by J-Damhuis** [comment]
I'm pretty sure I've done this now. I haven't tested it with very complex trees, but it did work for simpler ones.

**Comment by richelbilderbeek** [comment]
That would be very impressive! Will take a look now!

**Comment by richelbilderbeek** [comment]
I have taken a look at `PBD`. I am impressed by the elegant solution you found and the conciseness of the tests. 

Convincing others, however, can still be improved:
 * write a vignette that demonstrates the five sampling methods
 * test (yes, add another test) that tests if `shortest` always gives the shortest branch lengths. Tip: use `raket::pbd_find_scenario` :-)
 * (same for `longest`)

**Comment by richelbilderbeek** [comment]
Project is over, close Issue.
