### ISSUE TITLE
Probable project: how long will the full experiment take?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cer_raket#3]
Could you predict how long the full experiment will take to run? Will all runs finish within 10 days? How long does the simplest run take?

**Comment by richelbilderbeek** [comment]
Just randomly sample 10 parameter sets and run these on Peregrine. The time these take will be put in the log files.

**Comment by richelbilderbeek** [comment]
@richelbilderbeek prepares for Tuesday

**Comment by richelbilderbeek** [comment]
* [ ] make a protocol to measure the timings (e.g. which ones to pick?)
 * [ ] run the experiment

**Comment by richelbilderbeek** [comment]
I have just successfully run it on Peregrine. I choose to keep it a bit sloppy, so the bachelor students are forced to think :angel:

**Comment by J-Damhuis** [comment]
The longest it took for Peregrine to create an output file was 24 hours and 30 minutes before it got cancelled due to a Node Fail

**Comment by richelbilderbeek** [comment]
I assume you are aware of this:

Powerfailure at datacenter DUO

25 May 2018 12:58 11 KB
From:
Nap, W.K.
To:
[...]

    Unsubscribe

Dear Peregrine-users,

As you might have heard a large part of the city of Groningen has suffered a power-failure. This has unfortunately also affected our datacenter at DUO, and several systems have been rebooted, including the compute-nodes for the Peregrine-cluster.

We will try to get everything up again as soon as possible, and will keep you informed,

Kind regards,

Wim Nap

CIT-RUG

**Comment by J-Damhuis** [comment]
The longest it took the second time was just over 22 hours.

**Comment by richelbilderbeek** [comment]
Project is over, close Issue.
