### ISSUE TITLE
How to evaluate supervisor?

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/cer_raket#8]
I think not only the students are obliged to have feedback on their performance. Sadly, AFAIK, there is no grading/evaluation form for supervisors.

Perhaps other supervisors ( @mcrillo, @Neves-P , @TheoPannetier , @RaphSch ) agree and would like to think out this?

If I'd be allowed to suggest one form, I'd suggest an informal and anonymous evaluation, in which the student(s) are interviewed by someone else than their supervisor about the supervision they receive. The findings are summarized by the interviewer and sent to the supervisor after the students have received their grades.

**Comment by mcrillo** [comment]
I agree!

**Comment by Neves-P** [comment]
Sounds like a great idea 👍

**Comment by richelbilderbeek** [comment]
This will be done by adding questions to the evaluation at which the supervisors will be absent. Will need to make up questions...

**Comment by richelbilderbeek** [comment]
My suggestions, with brackets as intended:

 * What is the name of your supervisor (we really need a name here!):
 * What did your supervisor do, that you hope he/she keeps with future students?
 * What did your supervisor do, that you hope he/she will do less with future students?

**Comment by TheoPannetier** [comment]
Here are some suggestions of topics that could be addressed too :
- Meetings : frequency (sufficient / unsufficient ?), planning, content
- Guidance: would you have appreciated more freedom or conversely more guidance, in the project ?This can be relative to the content, but also the proceedings of the project.
- Scope of the project : do you think there was enough (time-wise) to do during the project, too much, or too few ? 
- Did the research project correspond to what was announced, or what you imagined you would do, from the initial presentation ? In a good or a bad way ?
- Interactions with you supervisor: was he or she friendly, rude ? 

I think questions should serve as guidelines for comments, but students should feel free overall to shape their feedback the way they want.

**Comment by richelbilderbeek** [comment]
I enjoy your suggestions @TheoPannetier ! I have mixed feeling of discussing these and/or merging our ideas, but I think we should do so before suggesting these to Rampal. Will do so tomorrow, when my head is clearer :angel:

**Comment by richelbilderbeek** [comment]
I will just email this to Rampal: easiest for me :angel:

**Comment by richelbilderbeek** [comment]
Sent an email, CC to Theo.

**Comment by richelbilderbeek** [comment]
Project is over, close Issue.
